# Site settings
title: Swazza's Blog
tag_text: Swazza's Blog
description: A responsive template for publishing single-page websites, articles that are easy on the eyes
url: "http://127.0.0.1:4000"

# Build settings
markdown: kramdown

exclude: ["README.md"]
